# Website base URL
baseURL = "https://letteredplans.earne.link"

# The name of this wonderful theme ;-).
theme = 'hugo-bearblog-fork'

# Google Analytics - let's not. see partials/custom_body.html
# googleAnalytics = "UA-111111111-1"

# Basic metadata configuration for your blog.
title = "Lettered Plans"
author = "earnest ma"
copyright = "Copyright © 2020, letteredplans."
languageCode = "en-US"

# Generate a nice robots.txt for SEO
enableRobotsTXT = true

[taxonomies]
  category = "categories"
  tag = "tags"

[permalinks]
  blog = "/:year/:month/:day-:slug"

[params]
  # The "description" of your website. This is used in the meta data of your generated html.
  description = "lettered plans blog + website: plan with me's, vlogs, and tutorials"

  # The path to your "favicon". This should be a square (at least 32px x 32px) png-file.
  # Hint: It's good practise to also put a "favicon.ico"-file into your "static"-folder.
  favicon = "/favicon.png"

  # These "images" are used for the structured data templates. This will show up, when
  # services like Twitter or Slack want to generate a preview of a link to your site.
  # See https://gohugo.io/templates/internal#twitter-cards and
  # https://gohugo.io/templates/internal#open-graph.
  images = ["/logo/share.png"]

  # Another "title" :-). This one is used as the site_name on the Hugo's internal
  # opengraph structured data template.
  # See https://ogp.me/ and https://gohugo.io/templates/internal#open-graph.
  title = "Lettered Plans"

  # This theme will, by default, inject a made-with-line at the bottom of the page.
  # You can turn it off, but we would really appreciate if you don’t :-).
  # hideMadeWithLine = true

# Fix raw html being ignored
# https://gohugo.io/news/0.60.0-relnotes/
[markup.goldmark.renderer]
      unsafe = true
